# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0cb0031c232af235d957896d3e285dd46335cbf80aaba46b2f65a4cc2aa1db6885ab5e5aece7c52135f51e5c71c29b9845ab6c4718c9f2c7fe118fbb70402d

test:
  secret_key_base: 418c08264f4c413e137653da026ce976d502e11a5376ab04e98afd78ec00454c8195086684475282c9edab2c17f31c4dae77f6212225026d1211ffdda5c5e013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
